version: "3"

services:
  test:
    build:
      context: .
    volumes:
      - .:/var/app
    command: sh -c "yarn jest"

  app:
    container_name: app
    build: .
    ports:
      - "3333:3333"
    expose:
      - 3333
    environment:
      - NODE_ENV=development
      - APP_PORT=3333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
    command: yarn dev:server
    volumes:
      - .:/var/app
    links:
      - redis

  redis:
    container_name: redis_dev
    image: redis
    volumes:
      - ./data:/redis/db
    ports:
      - "6379:6379"


